/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackSlideTime: typeof import('./src/components/backSlideTime.vue')['default']
    DaySlide: typeof import('./src/components/daySlide.vue')['default']
    Icon: typeof import('./src/components/icon.vue')['default']
    Needle: typeof import('./src/components/needle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Time: typeof import('./src/components/time.vue')['default']
  }
}
